//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int FromAccountID { get; set; }
        public int ToAccountID { get; set; }
        public decimal TransactionAmount { get; set; }
        public decimal FromBalance { get; set; }
        public decimal ToBalance { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
